# https://golangci-lint.run/usage/configuration/
run:

linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
#  enable-all: true
  disable-all: true
  enable:
    - deadcode
#    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
#    - unused
    - varcheck
linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake
        xml: snake
        bson: snake
        avro: snake
        mapstructure: snake