apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: example
build:
  artifacts:
    - image: example/hello
      context: build/hello
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deployments/kubernetes/hello/deployment.yaml
      - deployments/kubernetes/hello/service.yaml
