apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: example
build:
  artifacts:
    - image: example/example
      context: build/example
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deployments/kubernetes/example/deployment.yaml
      - deployments/kubernetes/example/service.yaml
      - deployments/kubernetes/example/ingress.yaml
