// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/maguowei/example/internal/example/domain/repository/ent/example"
	"github.com/maguowei/example/internal/example/domain/repository/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exampleMixin := schema.Example{}.Mixin()
	exampleMixinFields0 := exampleMixin[0].Fields()
	_ = exampleMixinFields0
	exampleFields := schema.Example{}.Fields()
	_ = exampleFields
	// exampleDescCreatedAt is the schema descriptor for created_at field.
	exampleDescCreatedAt := exampleMixinFields0[0].Descriptor()
	// example.DefaultCreatedAt holds the default value on creation for the created_at field.
	example.DefaultCreatedAt = exampleDescCreatedAt.Default.(func() time.Time)
	// exampleDescUpdatedAt is the schema descriptor for updated_at field.
	exampleDescUpdatedAt := exampleMixinFields0[1].Descriptor()
	// example.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	example.DefaultUpdatedAt = exampleDescUpdatedAt.Default.(func() time.Time)
	// example.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	example.UpdateDefaultUpdatedAt = exampleDescUpdatedAt.UpdateDefault.(func() time.Time)
}
