openapi: 3.0.1
info:
  title: example
  description: example
  version: 1.0.0
servers:
  - url: /
paths:
  /:
    get:
      tags:
        - index
      responses:
        200:
          description: index page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hello'
              examples:
                simple:
                  summary: example
                  value: { "msg": "hello world!" }
        default:
          description: generic error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /health:
    get:
      tags:
        - health
      responses:
        200:
          description: app health page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hello'
              examples:
                ok:
                  summary: health ok
                  value: { "msg": "ok" }
                err:
                  summary: health err
                  value: { "msg": "err" }
        default:
          description: generic error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    hello:
      required:
        - msg
      type: object
      properties:
        msg:
          type: string
    ErrorModel:
      required:
        - msg
      type: object
      properties:
        code:
          type: integer
          format: int64
        msg:
          type: string
